# Mensajes principales
messages:
  # El mensaje que se enviará al chat global
  stream_message:
    - '&a¡El streamer &e%player% &aestá en directo!'
    - '&a&lPlataforma: &b%platform%'
    - '&a&lEnlace: &7%link%'
  
  # Mensaje de error si el jugador no tiene el permiso necesario
  no_permission: '&cNo tienes permiso para usar este comando.'
  
  # Mensaje de error si el comando se usa de forma incorrecta
  usage: '&cUso incorrecto del comando: /directo <link>'
  
  # Mensaje de cooldown
  cooldown_message: '&cDebes esperar %cooldown% segundos para volver a usar el comando.'

# Cooldown en segundos
cooldown: 300
