permission: "ravenstream.use"

cooldown-seconds: 60

cooldown-message:
  - "&cDebes esperar {time} segundos antes de usar este comando de nuevo."

no-permission-message:
  - "&cNo tienes permiso para usar este comando."

platforms:
  twitch:
    - "&5[Directo] &f{player} est치 en vivo en &dTwitch&f:"
    - "&e{link}"
  youtube:
    - "&c[Directo] &f{player} est치 en vivo en &cYouTube&f:"
    - "&e{link}"
  kick:
    - "&a[Directo] &f{player} est치 en vivo en &aKick&f:"
    - "&e{link}"
  tiktok:
    - "&d[Directo] &f{player} est치 en vivo en &dTikTok&f:"
    - "&e{link}"
